packages:
  - locales
  - packages/*
  - components/**
  - '!**/test/**'

catalogs:
  dev:
    '@vitejs/plugin-vue': ^6.0.5
    '@vitejs/plugin-vue-jsx': ^5.1.5
    '@vitejs/devtools': ^0.1.0
    ant-design-vue: ^4.2.6
    vue: ^3.5.24
    vite: ^8.0.0
    tailwind-merge: ^3.4.0
    tailwindcss: ^3.4.4
    tsdown: ^0.21.3
    lodash-es: ^4.17.21
  types:
    '@types/lodash-es': ^4.17.12

ignoredBuiltDependencies:
  - '@bundled-es-modules/glob'
  - '@sentry/cli'
  - core-js
  - esbuild
  - style-dictionary
  - vue-demi

onlyBuiltDependencies:
  - electron

packageExtensions:
  browser-plugin:
    dependencies:
      vite: ^5.4.21
