/**
 * tag map in chinese
 */
export const TagMap = {
  html: '根元素',
  body: '主体元素',
  div: '块元素',
  span: '行元素',
  p: '段落',
  a: '链接',
  address: '地址',
  area: '热点区域',
  article: '文章',
  audio: '音频',
  b: '强调文本',
  button: '按钮',
  canvas: '画布',
  code: '代码块',
  col: '表格列',
  colgroup: '表格列组',
  datalist: '数据列表',
  details: '详细信息',
  dialog: '对话框',
  em: '强调元素',
  embed: '外部内容',
  footer: '页脚',
  form: '表单',
  frame: '嵌入文档',
  h1: '标题',
  h2: '标题',
  h3: '标题',
  h4: '标题',
  h5: '标题',
  h6: '标题',
  header: '页眉',
  hr: '主题分割',
  i: '术语文本',
  iframe: '嵌入文档',
  img: '图像',
  input: '输入',
  textarea: '输入域',
  label: '说明',
  li: '列表',
  main: '主体',
  mark: '突出文本',
  menu: '菜单',
  nav: '导航',
  ol: '有序列表',
  picture: '图像',
  progress: '进度条',
  select: '下拉框',
  summary: '摘要',
  table: '表格',
  tr: '表格行',
  td: '单元格',
  ul: '无序列表',
  video: '视频',
}
/**
 * input type map in chinese
 */
export const InputTypeMap = {
  text: '输入框',
  password: '密码',
  checkbox: '复选框',
  radio: '单选框',
  submit: '提交按钮',
  reset: '重置',
  button: '按钮',
  file: '文件',
  hidden: '隐藏',
  image: '图像',
  email: '电子邮件',
  url: '网址',
  tel: '电话号码',
  number: '数字',
  search: '搜索',
  range: '范围',
  date: '日期',
  time: '时间',
  month: '月份',
  week: '周',
  datetime: '日期和时间',
  color: '颜色',
}
