const mirrorList = [
  { value: 'https://pypi.mirrors.ustc.edu.cn/simple/', disabled: false },
  { value: 'https://mirrors.aliyun.com/pypi/simple', disabled: false },
  { value: 'https://pypi.tuna.tsinghua.edu.cn/simple', disabled: false },
  { value: 'https://pypi.python.org/simple', disabled: false },
  { value: 'http://pypi.douban.com/simple/', disabled: false },
]
const pythonLoadingMap = {
  installing: {
    closable: false,
    icon: 'installing.svg',
    loadingText: '正在安装，请稍后...',
    okBtn: false,
    cancleBtn: false,
  },
  installFail: {
    closable: false,
    icon: 'installFail.svg',
    loadingText: '安装失败',
    showMsg: true,
    okBtn: true,
    cancleBtn: false,
  },
  installSuccess: {
    closable: false,
    icon: 'installSuccess.svg',
    loadingText: '安装成功',
    showMsg: true,
    okBtn: true,
    cancleBtn: false,
  },
  uninstalling: {
    closable: false,
    icon: 'uninstalling.svg',
    loadingText: '正在卸载，请稍后...',
    okBtn: false,
    cancleBtn: false,
  },
  uninstallFail: {
    closable: false,
    icon: 'uninstalling.svg',
    loadingText: '卸载失败',
    showMsg: true,
    okBtn: true,
    cancleBtn: false,
  },
  uninstallSuccess: {
    closable: false,
    icon: 'uninstalling.svg',
    loadingText: '卸载成功',
    showMsg: true,
    okBtn: true,
    cancleBtn: false,
  },
  upgrading: {
    closable: false,
    icon: 'upgrading.svg',
    loadingText: '正在升级，请稍后...',
    okBtn: false,
    cancleBtn: false,
  },
  upgradeFail: {
    closable: false,
    icon: 'upgrading.svg',
    loadingText: '升级失败',
    showMsg: true,
    okBtn: true,
    cancleBtn: false,
  },
  upgradeSuccess: {
    closable: false,
    icon: 'upgrading.svg',
    loadingText: '升级成功',
    showMsg: true,
    okBtn: true,
    cancleBtn: false,
  },
  uninstallTip: {
    closable: true,
    headerText: '提示',
    icon: 'uninstalling.svg',
    loadingText: '是否确认卸载依赖包？',
    okBtn: true,
    okFn: 'uninstallPackage',
    cancleBtn: true,
  },
  upgradePythonTip: {
    closable: true,
    headerText: '提示',
    icon: 'upgradePythonPackage.svg',
    loadingText: '你要升级依赖包至最新版吗',
    okBtn: true,
    okFn: 'upgradePackage',
    cancleBtn: true,
  },
}

export {
  mirrorList,
  pythonLoadingMap,
}
