export const BOOT = 'boot' // 启动页
export const LOGIN = 'login' // 登录页
export const ARRANGE = 'arrange' // 编排页
export const DESIGNER = 'designer' // 设计器
export const ACTUATOR = 'actuator' // 执行器
export const APPLICATIONMARKET = 'applicationMarket'
export const AIASSISTANT = 'aiAssistant'
export const PROJECTMANAGEMENT = 'projectManagement' // 工程管理
export const COMPONENTMANAGEMENT = 'componentManagement' // 组件管理
export const COMPONENTCREATED = 'componentCreated' // 创建的组件
export const PROJECTCREATED = 'projectCreated' // 创建的工程
export const PROJECTMARKET = 'projectMarket' // 获取的工程
export const MODULEMANAGEMENT = 'moduleManagement' // 组件管理
export const TEMPLATEMANAGEMENT = 'templateManagement' // 模板管理
export const ROBOTLIST = 'robots' // 应用列表
export const EXCUTELIST = 'executionRecords' // 执行记录
export const TASKLIST = 'scheduleTasks' // 计划任务
export const QUEUELIST = 'queueList' // 队列列表

export const SPARKDESKFLOW = 'flow' // 流程助手
export const SPARKDESKDATA = 'data'
export const SPARKDESKKNOW = 'book'
export const MARKETLIST = 'marketList'
export const MARKETMY = 'myPublic'
export const TEAMMARKETS = 'teamMarkets'
export const TEAMMARKETMANAGE = 'teamMarketManage'
export const OFFICIALMARKET = 'officialMarket'
export const APPLICATION = 'application'
export const RECOMMEND = 'recommendApp'
export const EDITORPAGE = 'editorPage'
export const SMARTCOMPONENT = 'smartComponent'
